### ISSUE TITLE
ビルドに失敗してしまう問題

### ISSUE THREAD

**Issue by AI-Avalon** [Anteccq/ApexRandomGachaBot#1]
`ビルドを開始しました...
1>------ ビルド開始: プロジェクト: ApexRandomGachaBot, 構成: Debug Any CPU ------
1>C:\Program Files\dotnet\sdk\6.0.202\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.DefaultItems.targets(134,5): warning NETSDK1182: Visual Studio 2019 で .NET 6.0 をターゲットにすることはサポートされていません。
1>CSC : warning CS8032: アナライザー System.Text.Json.SourceGeneration.JsonSourceGenerator のインスタンスは C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.4\analyzers\dotnet\cs\System.Text.Json.SourceGeneration.dll (ファイルまたはアセンブリ 'Microsoft.CodeAnalysis, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'、またはその依存関係の 1 つが読み込めませんでした。指定されたファイルが見つかりません。) から作成できません。
1>D:\Documents\ApexRandomGachaBot-main\ApexRandomGachaBot\BotInfo.cs(1,29,1,30): error CS1514: { が必要です
1>D:\Documents\ApexRandomGachaBot-main\ApexRandomGachaBot\BotInfo.cs(6,2,6,2): error CS1513: } が必要です
1>D:\Documents\ApexRandomGachaBot-main\ApexRandomGachaBot\CommonCommandModule.cs(4,29,4,30): error CS1514: { が必要です
1>D:\Documents\ApexRandomGachaBot-main\ApexRandomGachaBot\CommonCommandModule.cs(37,2,37,2): error CS1513: } が必要です
1>D:\Documents\ApexRandomGachaBot-main\ApexRandomGachaBot\Configuration\ConfigRepository.cs(3,43,3,44): error CS1514: { が必要です
1>D:\Documents\ApexRandomGachaBot-main\ApexRandomGachaBot\Configuration\ConfigRepository.cs(47,2,47,2): error CS1513: } が必要です
1>D:\Documents\ApexRandomGachaBot-main\ApexRandomGachaBot\Configuration\IConfigRepository.cs(1,43,1,44): error CS1514: { が必要です
1>D:\Documents\ApexRandomGachaBot-main\ApexRandomGachaBot\Configuration\IConfigRepository.cs(6,2,6,2): error CS1513: } が必要です
1>D:\Documents\ApexRandomGachaBot-main\ApexRandomGachaBot\Gacha\Legends\ILegendGacha.cs(1,43,1,44): error CS1514: { が必要です
1>D:\Documents\ApexRandomGachaBot-main\ApexRandomGachaBot\Gacha\Legends\ILegendGacha.cs(7,2,7,2): error CS1513: } が必要です
1>D:\Documents\ApexRandomGachaBot-main\ApexRandomGachaBot\Gacha\Legends\Legend.cs(1,43,1,44): error CS1514: { が必要です
1>D:\Documents\ApexRandomGachaBot-main\ApexRandomGachaBot\Gacha\Legends\Legend.cs(28,2,28,2): error CS1513: } が必要です
1>D:\Documents\ApexRandomGachaBot-main\ApexRandomGachaBot\Configuration\Config.cs(1,43,1,44): error CS1514: { が必要です
1>D:\Documents\ApexRandomGachaBot-main\ApexRandomGachaBot\Gacha\Legends\LegendGacha.cs(1,43,1,44): error CS1514: { が必要です
1>D:\Documents\ApexRandomGachaBot-main\ApexRandomGachaBot\Gacha\Weapons\IWeaponGacha.cs(1,43,1,44): error CS1514: { が必要です
1>D:\Documents\ApexRandomGachaBot-main\ApexRandomGachaBot\Gacha\Module\GachaCommandModule.cs(6,42,6,43): error CS1514: { が必要です
1>D:\Documents\ApexRandomGachaBot-main\ApexRandomGachaBot\Gacha\Module\GachaCommandModule.cs(127,2,127,2): error CS1513: } が必要です
1>D:\Documents\ApexRandomGachaBot-main\ApexRandomGachaBot\Gacha\Weapons\WeaponGacha.cs(1,43,1,44): error CS1514: { が必要です
1>D:\Documents\ApexRandomGachaBot-main\ApexRandomGachaBot\Gacha\Weapons\WeaponGacha.cs(36,2,36,2): error CS1513: } が必要です
1>D:\Documents\ApexRandomGachaBot-main\ApexRandomGachaBot\Gacha\Weapons\WeaponGachaMode.cs(1,43,1,44): error CS1514: { が必要です
1>D:\Documents\ApexRandomGachaBot-main\ApexRandomGachaBot\Gacha\Weapons\WeaponGachaMode.cs(17,2,17,2): error CS1513: } が必要です
1>D:\Documents\ApexRandomGachaBot-main\ApexRandomGachaBot\Logging\LogSeverityExtensions.cs(4,37,4,38): error CS1514: { が必要です
1>D:\Documents\ApexRandomGachaBot-main\ApexRandomGachaBot\Logging\LogSeverityExtensions.cs(19,2,19,2): error CS1513: } が必要です
1>D:\Documents\ApexRandomGachaBot-main\ApexRandomGachaBot\Runner.cs(9,29,9,30): error CS1514: { が必要です
1>D:\Documents\ApexRandomGachaBot-main\ApexRandomGachaBot\Runner.cs(67,2,67,2): error CS1513: } が必要です
1>D:\Documents\ApexRandomGachaBot-main\ApexRandomGachaBot\obj\Debug\net6.0\ApexRandomGachaBot.GlobalUsings.g.cs(2,1,2,42): error CS8652: 機能 'グローバル using ディレクティブ' は現在、プレビュー段階であり、*サポートされていません*。プレビュー機能を使用するには、'preview' 言語バージョンを使用してください。
1>D:\Documents\ApexRandomGachaBot-main\ApexRandomGachaBot\obj\Debug\net6.0\ApexRandomGachaBot.GlobalUsings.g.cs(3,1,3,29): error CS8652: 機能 'グローバル using ディレクティブ' は現在、プレビュー段階であり、*サポートされていません*。プレビュー機能を使用するには、'preview' 言語バージョンを使用してください。
1>D:\Documents\ApexRandomGachaBot-main\ApexRandomGachaBot\obj\Debug\net6.0\ApexRandomGachaBot.GlobalUsings.g.cs(4,1,4,49): error CS8652: 機能 'グローバル using ディレクティブ' は現在、プレビュー段階であり、*サポートされていません*。プレビュー機能を使用するには、'preview' 言語バージョンを使用してください。
1>D:\Documents\ApexRandomGachaBot-main\ApexRandomGachaBot\obj\Debug\net6.0\ApexRandomGachaBot.GlobalUsings.g.cs(5,1,5,32): error CS8652: 機能 'グローバル using ディレクティブ' は現在、プレビュー段階であり、*サポートされていません*。プレビュー機能を使用するには、'preview' 言語バージョンを使用してください。
1>D:\Documents\ApexRandomGachaBot-main\ApexRandomGachaBot\obj\Debug\net6.0\ApexRandomGachaBot.GlobalUsings.g.cs(6,1,6,34): error CS8652: 機能 'グローバル using ディレクティブ' は現在、プレビュー段階であり、*サポートされていません*。プレビュー機能を使用するには、'preview' 言語バージョンを使用してください。
1>D:\Documents\ApexRandomGachaBot-main\ApexRandomGachaBot\obj\Debug\net6.0\ApexRandomGachaBot.GlobalUsings.g.cs(7,1,7,38): error CS8652: 機能 'グローバル using ディレクティブ' は現在、プレビュー段階であり、*サポートされていません*。プレビュー機能を使用するには、'preview' 言語バージョンを使用してください。
1>D:\Documents\ApexRandomGachaBot-main\ApexRandomGachaBot\obj\Debug\net6.0\ApexRandomGachaBot.GlobalUsings.g.cs(8,1,8,39): error CS8652: 機能 'グローバル using ディレクティブ' は現在、プレビュー段階であり、*サポートされていません*。プレビュー機能を使用するには、'preview' 言語バージョンを使用してください。
1>D:\Documents\ApexRandomGachaBot-main\ApexRandomGachaBot\obj\Debug\net6.0\ApexRandomGachaBot.GlobalUsings.g.cs(9,1,9,45): error CS8652: 機能 'グローバル using ディレクティブ' は現在、プレビュー段階であり、*サポートされていません*。プレビュー機能を使用するには、'preview' 言語バージョンを使用してください。
1>D:\Documents\ApexRandomGachaBot-main\ApexRandomGachaBot\Gacha\Legends\LegendGacha.cs(22,2,22,2): error CS1513: } が必要です
1>D:\Documents\ApexRandomGachaBot-main\ApexRandomGachaBot\Configuration\Config.cs(3,49,3,49): error CS1513: } が必要です
1>D:\Documents\ApexRandomGachaBot-main\ApexRandomGachaBot\Gacha\Weapons\IWeaponGacha.cs(8,2,8,2): error CS1513: } が必要です
1>D:\Documents\ApexRandomGachaBot-main\ApexRandomGachaBot\Gacha\Weapons\Weapon.cs(1,43,1,44): error CS1514: { が必要です
1>D:\Documents\ApexRandomGachaBot-main\ApexRandomGachaBot\Gacha\Weapons\Weapon.cs(60,2,60,2): error CS1513: } が必要です
1>プロジェクト "ApexRandomGachaBot.csproj" のビルドが終了しました -- 失敗。
========== ビルド: 0 正常終了、1 失敗、0 更新不要、0 スキップ ==========
`
こちらの環境は.netが入ってるかと思います。
VisualStudio 2019でBuildしました。
C#初心者のただのAPEX好きなので、とんちんかんな質問していてもお許しください。
また、長くなりそうで、詳しく説明していただけそうなのであれば、 AI Avalon#7850 こちらにでも教えていただけると嬉しいです。

**Comment by Anteccq** [comment]
@AI-Avalon 
あー... `.NET 6` の正式サポートは Visual Studio 2022  からでした。（すいません失念してました）
なので新しく Visual Studio 2022 を入れて頂けるとやりやすいかと思います。

ですが、.NET 6 SDK だけあればわざわざ大きな Visual Studio 2022 を入れる手間は必要ないです。ので、以下の手順を行ってみて頂けますか?
(もちろん、以下の手順をするよりも Visual Studio 2022 を入れて頂いたほうが今までと同じ手順でやりやすいかと思います)

1. .NET SDK 6.0 をインストールする https://dotnet.microsoft.com/ja-jp/download/dotnet/6.0
2. `ApexRandomGachaBot.csproj` ファイルがあるディレクトリまで console や powershell (terminal 等)で移動する。
3. `dotnet build -c Release` コマンドを実行
4. bin/Debug/net6.0 ディレクトリに移動
5. `dotnet .\ApexRandomGachaBot.dll` (初回起動時は即終了します。)
6. config.json ファイルのToken にDiscrod のトークンを入力。
7. 再度 `dotnet .\ApexRandomGachaBot.dll`

で起動できると思います。

**Comment by AI-Avalon** [comment]
上記の通りにやったところ、うまくBuildすることができました！
ですが今後のことも考えて2019である理由もないので2022にアップデートしてみることにしました！
意見聞いていただきありがとうございました！
